version: 1.0.{build}
branches:
  only:
  - master
  - eric
image: Visual Studio 2015
configuration: release
platform: x64
environment:
  PYTHON: C:/Python37-x64
  PATH: C:/Program Files/OneFLOW/bin;C:/Program Files/OneFLOW;"C:/Program Files/CMake/bin/";C:/Program Files/Microsoft MPI/Bin;%PATH%
build_script:
- ps: >-
    powershell ci/appveyor/installMPI.ps1
    
    powershell ci/appveyor/installCMAKE.ps1
    
    powershell ci/appveyor/InstallMETIS.ps1
    
    powershell ci/appveyor/installHDF5.ps1
    
    powershell ci/appveyor/installCGNS.ps1
    
    powershell ci/appveyor/buildOneFLOW.ps1
test_script:
- cmd: >-
    ECHO this is batch
   
    dir
    
    dir "C:/Program Files"

    dir "C:/Tools"
    
    OneFLOW
    
    cd test
    
    ECHO %PATH%